@startuml
participant "Control Task" as ctrl
participant "CAN Manager" as can
participant "Sensor Task" as sensor
participant "Actuator" as act
participant "Hardware" as hw

ctrl -> sensor ++ : request_sensor_data()
sensor -> hw : read_adc()
hw --> sensor : raw_value
sensor --> ctrl -- : processed_data

ctrl -> ctrl : run_control_algorithm()

ctrl -> act ++ : set_actuator(value)
act -> hw : set_pwm(duty_cycle)
act --> ctrl --

ctrl -> can ++ : send_status_message()
can -> hw : can_transmit()
can --> ctrl --

== 10ms later ==

ctrl -> sensor ++ : request_sensor_data()
sensor -> hw : read_adc()
hw --> sensor : raw_value
sensor --> ctrl -- : processed_data

note over ctrl : Cycle repeats every 10ms
@enduml
