site_name: Network IDS Project
site_description: ML-based Network Intrusion Detection System
site_author: Sivaramasubramanian Sundararaj

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.sections
    - navigation.expand

extra:
  toc:
    visible: false

extra_css:
  - css/custom.css

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Tools Installation: tools_installation.md
  - System Requirements: Requirements/SystemRequirements.md

plugins:
  - search
  - git-revision-date-localized:
      type: custom
      custom_format: "%d-%b-%Y"
      timezone: Europe/Berlin
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - extra

docs_dir: docs

# Enable raw HTML/JavaScript in markdown
use_directory_urls: true

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js