@startuml
participant "Control Task" as ctrl
participant "CAN Manager" as can
participant "Sensor Task" as sensor
participant "Actuator" as act
participant "Hardware" as hw

activate ctrl
ctrl -> sensor : request_sensor_data()
activate sensor
sensor -> hw : read_adc()
hw --> sensor : raw_value
sensor --> ctrl : processed_data
deactivate sensor

ctrl -> ctrl : run_control_algorithm()
ctrl -> act : set_actuator(value)
activate act
act -> hw : set_pwm(duty_cycle)
deactivate act

ctrl -> can : send_status_message()
activate can
can -> hw : can_transmit()
deactivate can
deactivate ctrl

== 10ms later ==
activate ctrl
note over ctrl : Next control cycle
@enduml