name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"

permissions:
  contents: write 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for git-revision-date plugin

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre graphviz
          sudo apt-get install -y plantuml

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material
          pip install mkdocs-git-revision-date-localized-plugin
          pip install pymdown-extensions
          pip install mkdocs-build-plantuml-plugin

      - name: Generate System Requirements
        run: |
          cd docs/Requirements
          python generate_requirements_page.py
          cd ../..  # Return to root

      - name: Deploy docs
        run: mkdocs gh-deploy --force